//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAPIEjemplo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoEmpleado
    {
        public int RowID { get; set; }
        public int NoEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Puesto { get; set; }
        public int Rol { get; set; }
        public string Usuario { get; set; }
        public string pass { get; set; }
    
        public virtual Cat_Roles Cat_Roles { get; set; }
    }
}
